workflows:
  android-dev:
    name: Android Development
    instance_type: mac_mini_m1
    max_build_duration: 90
    environment:
      groups:
        - google_credentials
      flutter: stable
      android_signing:
        - golub_keystore
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '{feature}/*'
          include: true
          source: false
    scripts:
      - name: Get Flutter dependencies
        script: flutter packages pub get
     # - name: Build APK
     #   script: flutter build apk --release --build-name=1.0.0 --build-number=2
      - name: Build App Bundle
        script: flutter build appbundle --release --build-name=1.0.0 --build-number=2
    artifacts:
      #- build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        changes_not_sent_for_review: true
      email:
        recipients:
          - "denisdubov88@gmail.com"
        notify:
          success: true

