name: golub
description: Messenger

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: 12.1.0
  flutter_svg: 2.0.9
  intl: 0.18.1
  freezed: 2.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  intl_utils: 2.8.5
  build_runner: 2.4.6

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
   - assets/icons/
   - assets/logo/

  fonts:
   - family: Ubuntu
     fonts:
       - asset: assets/fonts/ubuntu/ubuntu-regular.ttf
       - asset: assets/fonts/ubuntu/ubuntu-medium.ttf
         weight: 500
   - family: Roboto
     fonts:
       - asset: assets/fonts/roboto/roboto-regular.ttf

